[package]
name = "mule"
version = "0.1.0"
edition = "2021"

[build-dependencies]
glob = "0.3.1"
peacock = { git = "https://github.com/nucleus-labs/peacock", rev = "be5f78fa156eddc759e7d4c27b615f80f50392c6", features = ["build"] }

[dependencies]
peacock = { git = "https://github.com/nucleus-labs/peacock", rev = "be5f78fa156eddc759e7d4c27b615f80f50392c6" }
derive_more = { version = "1.0.0", features = [ "from" ] }
iced = "0.13.1"
nmea = "0.7.0"
